### ISSUE TITLE
Windows path prevents vue-test-loader from working

### ISSUE THREAD

**Issue by onexdata** [eddyerburgh/vue-test-loader#1]
When building any project using vue-test-loader in windows, the way index.js is written (line 4 uses a hard-coded '/' instead of node's path module), the full path is used when building the destination.

To fix this and make it compatible with all operating systems, replace the latest index.js with this (adding path, using it in const filename = and changing the const path to const dest at the bottom):

const fs = require('fs')
const path = require('path')

module.exports = function(source) {
  const filename = require('path').parse(this.resourcePath).name

  const extension = '.spec.js'
  const dir = `${this.context}/${this.options.extension || '__tests__'}`

  if (!fs.existsSync(dir)){
      fs.mkdirSync(dir);
  }

  const dest = `${dir}/${filename}${extension}`
  fs.writeFileSync(dest, source.replace(/('..\/)/g, "'../../").replace(/('.\/)/g, "'../").trim())
  return source
};

**Comment by eddyerburgh** [comment]
The fix is released in 0.4.1 😀
